---
title: "Birds"
author: "Tamara"
date: "18 Juni 2019"
output: html_document
---

# Load Packages
```{r}
library(tidyverse)
library(summarytools)
library(hrbrthemes)
library(purrr)
library(plotly)
```

# Read Data
```{r}
bird_counts <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-18/bird_counts.csv")
```

# Summary 
```{r}
view(dfSummary(bird_counts))
```

# 
```{r}
bird_counts %>%
  group_by(year) %>%
  summarise(n = sum(how_many_counted)) %>%
  ggplot() +
  geom_col(aes(x = year, y = n))


common_birds <- bird_counts %>%
  filter(year >= 1979) %>%
  group_by(year) %>%
  top_n(5, how_many_counted) %>%
  ungroup() %>%
  count(species) %>%
  pull(species)

bird_counts2 <- bird_counts %>%
  filter(species %in% common_birds,
         year >= 1979) %>%
  select(species, year, n = how_many_counted)

ggplot(bird_counts2) +
  geom_tile(aes(x = year, y = species, fill = n)) +
  labs(title = "Which Bird might be seen/heard at Christmas?",
       subtitle = "Bird Counts from 1979 to 2017 in Hamilton (Canada)",
       caption = "Bird Studies Canada (twitter handle: @BirdsCanada)") +
  theme_ipsum_rc() 

ggsave("birds.png", height = 300, width = 300, units = "mm")

```

# Most Common Bird - European Starling
```{r}
bird_counts %>%
  group_by(year) %>% 
  mutate(Starling = sum(how_many_counted)) %>%
  ungroup() %>% 
  mutate(Total = how_many_counted) %>%
  filter(species == "European Starling") %>%
  gather(bird, count, Total, Starling) %>%
  select(year, bird, count) %>%
  ggplot() +
  geom_line(aes(x = year, y = count, color = bird)) +
  scale_color_discrete(name = "Bird Counts", 
                    labels = c("Total Number of Birds", "European Starling")) +
  labs(title = "European Starling doesn't like Christmas in Canada anymore",
       subtitle = "Bird Counts from 1921 to 2017 in Hamilton (Canada)",
       caption = "Bird Studies Canada (twitter handle: @BirdsCanada)") +
  theme_ipsum_rc() +
  theme(legend.position = "bottom")

ggsave("starling.png", height = 200, width = 300, units = "mm")
```

# Most Common Bird - European Starling Animated
```{r}

bird_frame <- bird_counts %>%
  group_by(year) %>% 
  mutate(Total = sum(how_many_counted)) %>%
  ungroup() %>% 
  mutate(Starling = how_many_counted) %>%
  filter(species == "European Starling") %>%
  gather(bird, count, Total, Starling) %>%
  select(year, bird, count) %>%
  mutate(bird = fct_recode(bird, "European Starling" = "Starling",
                            "Total Number of Birds" = "Total")) %>%
  split(.$year) %>%
  accumulate(~bind_rows(.x, .y)) %>%
  bind_rows(.id = "frame")
  
p <- plot_ly(bird_frame) %>%
  add_lines(x = ~year, y = ~count, color = ~bird, frame = ~frame, showlegend = TRUE) %>%
  layout(title = "European Starling doesn't like Christmas in Canada anymore",
       legend = list(orientation = 'h', xanchor = "center", x = 0.5),
       xaxis = list(title = "\r\nYear"),
       annotations =  list(x = 1, y = -0.3, text = "Bird Studies Canada (twitter handle: @BirdsCanada)",  showarrow = F, xref='paper', yref='paper', font = list(size = 10),
      xanchor='right', yanchor='auto', xshift=0, yshift=0))%>%
  animation_slider(hide = TRUE) 

htmlwidgets::saveWidget(as_widget(p), "starling.html")
```


