---
title: "Phd Award"
author: "Tamara"
date: "9 Juni 2019"
output: html_document
---

# Load Packages
```{r}
library(tidyverse)
library(summarytools)
library(hrbrthemes)
library(gganimate)
```

# Read Data
```{r}
phd_field <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-19/phd_by_field.csv")
```

# View Data
```{r error = FALSE}
View(phd_field)
view(dfSummary(phd_field))
```

# Number of Phd per Broad Field over time
```{r warning = FALSE}
n_phd_year <- phd_field %>%
  group_by(broad_field, year) %>% 
  summarise(n = sum(n_phds, na.rm = TRUE)) %>% 
  ungroup() %>%
  mutate(broad_field = fct_relevel(str_to_title(broad_field), rev)) %>%
  mutate(broad_field = fct_relevel(broad_field, "Other"))

field_year_plot<- ggplot(n_phd_year, aes(x = broad_field,
                       y = n, 
                       fill = broad_field)) +
  geom_col() +
  geom_text(aes(label = as.integer(n)), hjust = -.2) +
  scale_fill_ipsum() +
  scale_y_continuous(limits = c(0, 30000)) +
  labs(title = "Number of PhD degrees awarded in the USA",
       subtitle = "By broad field in {frame_time}",
       caption = "Data by NSF",
       x = "",
       y = "Number of PhDs") +
  coord_flip() +
  theme_ipsum_rc() +
  theme(legend.position = "none",
        panel.grid.major.y = element_blank()) +
  transition_time(as.integer(year)) 


animate(field_year_plot, 
        fps = 1, duration = 10, 
        height = 500, width = 800)

anim_save("phds.gif")
```

# Psychology
```{r}
phd_field %>%
  filter(str_detect(major_field, "Psychology"), year %in% c(2008, 2017))  %>%
  group_by(year) %>%
  summarise(n = sum(n_phds, na.rm = TRUE))

phd_psych_year <- phd_field %>%
  filter(str_detect(major_field, "Psychology"), year %in% c(2008, 2017),
         !field %in% "Social sciences")  %>%
  mutate(field = str_to_title(field)) %>%
  spread(year, n_phds) %>%
  filter(!is.na(`2008`), !is.na(`2017`)) %>%
  mutate(n_diff = `2017`- `2008`) 

phd_psych <- phd_psych_year %>%
  gather(year, n_phds, `2017`,`2008`)


ggplot() +
  geom_segment(data = phd_psych_year, aes(x = fct_reorder(field, `2017`), xend = field, 
                   y = `2008`, yend = `2017`)) +
  geom_point(data = phd_psych, aes(x = fct_reorder(field, year), y = n_phds, color = as.factor(year) ))+
  labs(title = "What are the most studied Fields \nin Psychology?",
       subtitle = "Awarded PhDs in Psychology \nfrom 2008 and 2017 in the US",
       caption = "Data by NFS",
       x = "",
       y = "Number of PhDs") +
  coord_flip() +
  theme_ipsum_rc() +
  theme(legend.position = "bottom",
        legend.title = element_blank())
  
ggsave("psych.png", height = 200, width = 200, units = "mm")

```







