---
title: "Nobel Price Winners"
author: "Tamara"
date: "14 Mai 2019"
output: html_document
---

# Load Packages
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(countrycode)
library(CoordinateCleaner)
library(ggplot2)
library(maps)
library(hrbrthemes)
library(ggthemes)
library(summarytools)
library(stringr)
library(waffle)
```

# Read Data
```{r}
nobel_winners <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv")

```

# Glimpse Data
```{r include = FALSE}
view(dfSummary(nobel_winners))
```

# Data Manipulation
```{r}
nobel_winners %>%
  count(birth_country)

nobel <- nobel_winners %>%
  select(prize_year, category, prize_share, birth_date, birth_country, gender) %>% 
  mutate(birth_country = str_replace(birth_country, "\\)", "")) %>%
  separate(birth_country, into = c("birth_country2", "birth_country_current"), sep = "\\(") %>%
  mutate(birth_country_rec = ifelse(is.na(birth_country_current), birth_country2,   birth_country_current)) %>%
  select(-birth_country_current, -birth_country2) 

nobel <- nobel %>%
  mutate(birth_country_rec = case_when(birth_country_rec == "Bosnia and Herzegovina" ~ "Bosnia & Herzegovina", 
                                       birth_country_rec == "Czech Republic" ~ "Czechia",
                                       birth_country_rec == "East Timor" ~ "Timor-Leste", 
                                       birth_country_rec == "Guadeloupe Island" ~	"Guadeloupe",
                                       birth_country_rec == "Myanmar" ~ "Myanmar (Burma)", 
                                       birth_country_rec == "Northern Ireland" ~ "United Kingdom",
                                       birth_country_rec == "People's Republic of China" ~ "China", 
                                       birth_country_rec == "Republic of Macedonia" ~ "Macedonia",
                                       birth_country_rec == "Saint Lucia" ~ "St. Lucia",
                                       birth_country_rec == "Scotland" ~ "United Kingdom",
                                       birth_country_rec == "Trinidad" ~ "Trinidad & Tobago", 
                                       birth_country_rec == "United States of America" ~ "United States", 
                                       TRUE ~ birth_country_rec))

codelist_dat <- codelist %>%
  select(continent, country.name.en, iso3c)

nobel_country <- left_join(nobel, codelist_dat, by = c("birth_country_rec" = "country.name.en")) 

nobel_country %>%
  filter(is.na(iso3c)) %>%
  count(birth_country_rec)

coordinates_dat <- countryref %>%
  filter(type == "country") %>%
  group_by(iso3) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  select(iso3, centroid.lon, centroid.lat)

nobel_geo <- left_join(nobel_country, coordinates_dat, by = c("iso3c" = "iso3"))
```

# Map Number of Nobel Prizes by Country
```{r message = FALSE, warning = FALSE}
nobel_map <- nobel_geo %>%
  filter(!is.na(centroid.lon), !is.na(centroid.lat)) %>%
  add_count(iso3c)

world_dat <- map_data('world') %>%
  filter(region != "Antarctica") 

ggplot() +  
  geom_map(data = world_dat, map = world_dat, aes(x = long, y = lat, group = group, map_id=region), fill = "white", colour = "#7f7f7f", size=0.5) +
  geom_point(data = nobel_map, aes(x = centroid.lon, y = centroid.lat, size = n)) +
  labs(title = "Nobel Winners by Birth Country", 
       subtitle = "All Price Categories from 1901 to 2016 \nBubblesize indicates Number of Winners") +
  theme_ipsum_rc() +
  theme(axis.line = element_blank(), 
        axis.text = element_blank(), 
        axis.ticks = element_blank(), 
        axis.title = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        panel.spacing = unit(0, "lines"), 
        plot.background = element_blank(), 
        legend.position = "none")

ggsave("WinnersInWorld.png")

```

# Winners by Category and Gender
```{r message = FALSE, warning = FALSE}
nobel_gender <- nobel_geo %>%
  count(category, gender) %>%
  group_by(category) %>%
  mutate(n_category = sum(n)) %>%
  ungroup() %>%
  replace_na(list(gender = "Organization")) %>%
  unite(lable, c(category, n_category), sep = " n = ", remove = FALSE) 

ggplot(nobel_gender) +
  geom_waffle(aes(fill = gender, values = n)) +
  facet_wrap(~lable) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  ggthemes::scale_fill_tableau(name = NULL) +
  coord_equal() + 
  labs(title = "Distribution of Gender by Category",
       subtitle = "All Price Categories from 1901 to 2016") +
  theme_ipsum_rc(grid = "") +
  theme(legend.position = "bottom")

ggsave("CountryAndGender.png")
```





